### ISSUE TITLE
Waiting to connect to the Front context.

### ISSUE THREAD

**Issue by mansoorkhan96** [frontapp/logistics-tms-plugin#3]
I have followed the docs to setup this demo app. However when i access the url `http://localhost:5173` in local development, i get the message `Waiting to connect to the Front context.`. I have setup env secrets for Airtable and skipped the google maps to save some time.

Am i missing something?

I am guessing i need to put the Front App api keys somewhere?

**Comment by ncharanv** [comment]
Were you able to resolve this? I also followed the steps, but the plugin is not working as intended.

**Comment by mansoorkhan96** [comment]
> Were you able to resolve this? I also followed the steps, but the plugin is not working as intended.

No, not yet :(

**Comment by dugjason** [comment]
Hi Folks,
You might see that `Waiting to connect to the Front context.` warning if you're attempting to just navigate to `http://localhost:5173` in your browser. 

The way Front plugins work is by subscribing to an RxJS provider (provided by `app.frontapp.com` (or `<your-subdomain>.frontapp.com`)), so they can only receive data and connect to the Front context when used as a Front plugin. 

So in order to test them, you'll need to log in to Front, head to Settings > Developers > Create App. Create a Sidebar plugin, enter your app URL (`http://localhost:5173/`) and save, then head back into the Front application, and select that new plugin from the sidebar

**Comment by mansoorkhan96** [comment]
Maybe i am missing the whole point.

1) I have cloned this repo, ran npm install and npm run dev and navigate to http://localhost:5173/

2) I logged in to https://app.frontapp.com/ and created an app and added sidebar plugin
<img width="803" alt="image" src="https://github.com/frontapp/logistics-tms-plugin/assets/51432274/6cd6dd08-27c6-41a4-a0f0-d59b936a73dc">

3) You are saying `then head back into the Front application` is this same http://localhost:5173/ or some other application?

**Comment by dugjason** [comment]
Thanks @mansoorkhan96 , 
That's odd! Your configuration looks correct to me, and I was able to get a new instance running with a simple clone, npm install, npm run dev;

For point #3 - yes, I was saying that you should navigate back to https://app.frontapp.com and see the plugin in the sidebar;

<img width="1355" alt="Screenshot 2024-05-30 at 10 07 33 AM" src="https://github.com/frontapp/logistics-tms-plugin/assets/273718/55dadcbd-4d86-44a5-9823-2e24f0aa608b">
<img width="1343" alt="Screenshot 2024-05-30 at 10 08 04 AM" src="https://github.com/frontapp/logistics-tms-plugin/assets/273718/f5c846bd-5364-4267-8465-757b1e63395a">


If you take a look at your browser Dev Tools - do you see any issues reported in the **Console** or **Network** tabs related to the plugin?

**Comment by mansoorkhan96** [comment]
Hey, @dugjason 
Thank you for taking a look at it.

I dont see any errors in console.
<img width="1341" alt="image" src="https://github.com/frontapp/logistics-tms-plugin/assets/51432274/7f1d1c65-9028-4503-8e0a-1352b258a903">

However, my plugins page does not have Redirect URI?, Do you think could be an issue, i might have missed something.
<img width="1352" alt="image" src="https://github.com/frontapp/logistics-tms-plugin/assets/51432274/f73abeba-dce6-4393-852e-4ff2ebecf567">

**Comment by dugjason** [comment]
Hi @mansoorkhan96 , Regarding the console logs - can you head to app.frontapp.com, select the Logstics plugin, then open dev tools in that window?

I think the redirect URL part is irrelevant here and connected to how other parts of my sample app are configured.

**Reminder**; Front plugins work in the Front plugin sidebar **only**. If you open the plugin app in a browser not hosted in the Front plugin sidebar iframe, it can not access the Front context object passed from Front, so you should expect no context to be accessible.

**Comment by mansoorkhan96** [comment]
Hi @dugjason 

I can see some change now :) the sidebar plugin is showing a search field now and the iframe seems to be trying to connect to http://localhost:5173/

<img width="1352" alt="image" src="https://github.com/frontapp/logistics-tms-plugin/assets/51432274/ede07e41-2f94-42aa-a739-f02c45164b80">
<img width="1342" alt="image" src="https://github.com/frontapp/logistics-tms-plugin/assets/51432274/6f5cc032-91d4-4754-9574-1478ebb11d60">
